"""
Generate the icon assets used by the auto clicker.

Run this once whenever the icon design changes. It writes four files to the
repo root:

    icon.png    -- 512x512 PNG, source for everything else
    icon.ico    -- Windows multi-resolution icon, fed to PyInstaller --icon
    icon.icns   -- macOS bundle icon, fed to PyInstaller --icon
    _icon.py    -- tiny Python module holding the base64 PNG, imported by
                   autoclicker.py for the Tk window icon (works inside the
                   PyInstaller --onefile bundle without --add-data)

Usage:

    pip install Pillow
    python tools/make_icon.py
"""

import base64
from pathlib import Path

from PIL import Image, ImageDraw

SIZE = 512
ROOT = Path(__file__).resolve().parent.parent

BG = (30, 144, 255, 255)     # dodger blue
RING = (255, 255, 255, 255)
DOT = (255, 255, 255, 255)
CURSOR_FILL = (20, 20, 20, 255)
CURSOR_EDGE = (255, 255, 255, 255)


def draw_icon() -> Image.Image:
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    # Rounded square background tile.
    d.rounded_rectangle((20, 20, SIZE - 20, SIZE - 20), radius=80, fill=BG)

    # Concentric target rings + center dot.
    cx, cy = SIZE // 2, SIZE // 2 - 30
    d.ellipse((cx - 175, cy - 175, cx + 175, cy + 175), outline=RING, width=22)
    d.ellipse((cx - 105, cy - 105, cx + 105, cy + 105), outline=RING, width=20)
    d.ellipse((cx - 32, cy - 32, cx + 32, cy + 32), fill=DOT)

    # Cursor arrow sitting bottom-right of the target.
    pts = [
        (cx + 40, cy + 35),
        (cx + 40, cy + 215),
        (cx + 92, cy + 168),
        (cx + 122, cy + 228),
        (cx + 150, cy + 210),
        (cx + 118, cy + 152),
        (cx + 180, cy + 138),
    ]
    d.polygon(pts, fill=CURSOR_FILL, outline=CURSOR_EDGE)

    return img


def write_icon_module(png_path: Path) -> None:
    """Write _icon.py with the PNG embedded as base64.

    Storing the PNG bytes in the source means the packaged --onefile binary
    has the icon data without needing PyInstaller --add-data.
    """
    b64 = base64.b64encode(png_path.read_bytes()).decode("ascii")
    # Wrap to ~76 chars/line so the generated source is readable.
    wrapped = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))
    contents = (
        '"""Auto-generated by tools/make_icon.py. Do not edit by hand."""\n\n'
        f'ICON_PNG_B64 = (\n"""{wrapped}"""\n)\n'
    )
    (ROOT / "_icon.py").write_text(contents, encoding="utf-8")


def main() -> None:
    img = draw_icon()

    png_path = ROOT / "icon.png"
    img.save(png_path)

    # Windows ICO: ship the common Explorer resolutions in one file.
    img.save(
        ROOT / "icon.ico",
        sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
    )

    # macOS ICNS: Pillow picks the supported sizes from the source image.
    img.save(ROOT / "icon.icns")

    write_icon_module(png_path)

    print("wrote icon.png, icon.ico, icon.icns, _icon.py")


if __name__ == "__main__":
    main()
